### ISSUE TITLE
Exception when moving a folder: Undefined array key "Contents"

### ISSUE THREAD

**Issue by cweiske** [andersundsehr/aus_driver_amazon_s3#148]
When moving an existing folder via drag-and-drop into another folder, a 500 HTTP error is returned. The folder is moved, though.

Stack trace:
```
ErrorException: Warning: Undefined array key "Contents"
#47 /vendor/andersundsehr/aus-driver-amazon-s3/Classes/Driver/AmazonS3Driver.php(1549): AUS\AusDriverAmazonS3\Driver\AmazonS3Driver::getSubObjects
#46 /vendor/andersundsehr/aus-driver-amazon-s3/Classes/Driver/AmazonS3Driver.php(694): AUS\AusDriverAmazonS3\Driver\AmazonS3Driver::moveFolderWithinStorage
#45 /vendor/typo3/cms-core/Classes/Resource/ResourceStorage.php(2221): TYPO3\CMS\Core\Resource\ResourceStorage::moveFolder
#44 /vendor/typo3/cms-core/Classes/Resource/Folder.php(389): TYPO3\CMS\Core\Resource\Folder::moveTo
#43 /vendor/typo3/cms-core/Classes/Utility/File/ExtendedFileUtility.php(754): TYPO3\CMS\Core\Utility\File\ExtendedFileUtility::func_move
#42 /vendor/typo3/cms-core/Classes/Utility/File/ExtendedFileUtility.php(257): TYPO3\CMS\Core\Utility\File\ExtendedFileUtility::processData
#41 /vendor/typo3/cms-backend/Classes/Controller/File/FileController.php(248): TYPO3\CMS\Backend\Controller\File\FileController::main
```

Relevant code:
```
    protected function getSubObjects($identifier, $recursive = true, $filter = self::FILTER_ALL)
    {
        $result = $this->getListObjects($identifier);
        if (!is_array($result['Contents'])) {
            return [];
        }
```

----

This is with TYPO3 12.4.13 and andersundsehr/aus-driver-amazon-s3 1.12.1. This is old, but the same code is still in current master.

**Comment by cweiske** [comment]
This is probably a MinIO specific problem that might not affect S3, because when renaming a folder in MinIO, all children are renamed automatically.

`moveFolderWithinStorage` and `renameSubFolder` are similare but have one difference:

- `moveFolderWithinStorage` first renames the folder, then the children
- `renameSubFolder` first renames the children, then the folder.

A solution would be to make both behave the same: First rename children, then rename the folder.

**Comment by cweiske** [comment]
This happens when an **empty** folder is moved via drag and drop.
